# Generated by Django 3.1.7 on 2021-02-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('file', models.FileField(upload_to='')),
                ('translated', models.FileField(blank=True, null=True, upload_to='')),
                ('language', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name_plural': 'Repositories',
            },
        ),
    ]
